apiVersion: v1
kind: Service
metadata:
  name: portfolio-service-nodeport
spec:
  type: NodePort
  selector:
    app: portfolio
  externalTrafficPolicy: Local
  ports:
    - port: 80
      targetPort: 3000
      nodePort: 30007
